### ISSUE TITLE
Road to Next stable version

### ISSUE THREAD

**Issue by SebastianStehle** [OrleansContrib/Orleans.Providers.MongoDB#110]
Hi,

I think these are the tasks that should be solved:

* [x] Migrate to Orleans 7 (#100)
* [x] #111
* [x] Add support for Bson serializer. (#106)
* [x] Decide who is the main contributor / project admin from now on. (#107)
